name: dizzy_admin
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  cloud_firestore: ^5.4.0
  firebase_core: 
  extended_image: ^9.0.4
  flick_video_player: ^0.9.0
  file_picker: ^8.0.5
  firebase_storage: ^12.2.0
  firebase_auth: ^5.2.0
  flutter_native_splash: ^2.4.0
  path_provider: ^2.0.15
  assets_audio_player: ^3.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/font/
  fonts:
    - family: GilroyBold
      fonts:
        - asset: assets/font/Gilroy-Bold.ttf
    - family: GilroySemiBold
      fonts:
        - asset: assets/font/Gilroy-SemiBold.ttf
    - family: GilroyMedium
      fonts:
        - asset: assets/font/Gilroy-Medium.ttf
    - family: GilroyRegular
      fonts:
        - asset: assets/font/Gilroy-Regular.ttf
  uses-material-design: true
  generate: true

