name: dizzy_admin
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  cloud_firestore: ^5.4.0
  firebase_core: 
  extended_image: ^9.0.4
  flick_video_player: ^0.9.0
  audioplayers: 
  firebase_core_web: ^2.17.5
  file_picker: ^8.0.5
  cached_network_image: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/font/Gilroy-Bold.ttf


