// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCgqQj4NxFvnBkphV7mrZmn5c7DZqVBQJY",
      authDomain: "addpost-9b3e9.firebaseapp.com",
      projectId: "addpost-9b3e9",
      storageBucket: "addpost-9b3e9.appspot.com",
      messagingSenderId: "998001294501",
      appId: "1:998001294501:web:fc4c42abbd488edbd6614c",
      measurementId: "G-1VZMHNXSC0");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4O4F-F7dL5CYHgc-OQyNe2EBpg2GX4q8',
    appId: '1:998001294501:android:2bed5fa1bc68665bd6614c',
    messagingSenderId: '998001294501',
    projectId: 'addpost-9b3e9',
    storageBucket: 'addpost-9b3e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXz1hWSrnNh06Vj1A3cQJ0ShEs-djF150',
    appId: '1:998001294501:ios:9e3f9213cdf62a62d6614c',
    messagingSenderId: '998001294501',
    projectId: 'addpost-9b3e9',
    storageBucket: 'addpost-9b3e9.appspot.com',
    iosBundleId: 'com.example.addpost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgqQj4NxFvnBkphV7mrZmn5c7DZqVBQJY',
    appId: '1:998001294501:web:b1eb2b94a0b9d390d6614c',
    messagingSenderId: '998001294501',
    projectId: 'addpost-9b3e9',
    authDomain: 'addpost-9b3e9.firebaseapp.com',
    storageBucket: 'addpost-9b3e9.appspot.com',
    measurementId: 'G-XP86YM2VRQ',
  );
}
